version: '3.8'

services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"

volumes:
  db_vol:
