"""create user

Revision ID: 9ee75a0ee88d
Revises: 
Create Date: 2021-06-04 08:54:05.833367

"""
from typing import Tuple

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '9ee75a0ee88d'
down_revision = None
branch_labels = None
depends_on = None


def timestamps(indexed: bool = False) -> Tuple[sa.Column, sa.Column]:
    return (
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
            index=indexed,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
            index=indexed,
        ),
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column("id", sa.Integer, primary_key=True),
                    sa.Column("username", sa.String(255), unique=True, nullable=False),
                    sa.Column("email", sa.String(255), unique=True, nullable=False),
                    sa.Column("password", sa.Text, nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column("is_active", sa.Boolean(), nullable=False),
                    sa.Column("is_superuser", sa.Boolean(), nullable=False),
                    *timestamps(),
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
